### PR TITLE
feat: card supports image prop that readers passed image on top of the card

### LINKED ISSUE #57: Cards should accept an image prop
# Summary

Card right now only accepts `icons`. However, a true `Card` should have an `image` property that sits above the card and covers the entire spacing like so

CleanShot 2023-02-07 at 23 03 30@2x

### PR DESCRIPTION
**Pull request by sboy99**
This PR will enable card component accept image prop that is basically an image link. This image is passed to img element that renders an image.
closes #57 

#### Screenshots
Screenshot from 2023-02-14 18-30-28
Screenshot from 2023-02-14 18-31-09
Screenshot from 2023-02-14 18-35-23
Screenshot from 2023-02-14 18-35-58

### CODE REVIEW

**Comment by benjamin-shen** [comment]
@sboy99  try this: https://stackoverflow.com/a/71063465

**Review by tobias-mintlify — CHANGES_REQUESTED** [review]
When I ran it the image doesn't go to the edge of the card. Maybe there is something you didn't commit to the branch? For reference, I'm on Chrome on MacOS. I also ran `yarn` immediately before so I'm on the latest dependencies. 

Screen Shot 2023-02-14 at 9 04 39 AM

**Comment by sboy99** [comment]
That was a mistake while I was resolving merge conflict `className` in  component got replaced by previous so the changes were lost that image is not going to the edge. Is it working now?

**Review by tobias-mintlify — APPROVED** [review]
This looks good now thank you!

**Comment by tobias-mintlify** [comment]
@sboy99 can you make a PR in [mint](https://github.com/mintlify/mint) updating the [Card](https://github.com/mintlify/mint/blob/main/docs/components/card.mdx) docs with the new `image` property?

**Comment by sboy99** [comment]
Sure I will do

**Comment by sboy99** [comment]
Should I update only API reference or should I showcase A example component with API reference

**Pull request merged**
